# Generated by Django 5.2.1 on 2025-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_followers_remove_profile_profile_img_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileimg',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/show.jpg', upload_to='post_images'),
        ),
    ]
